services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Pass VITE_API_URL as a build arg
      args:
        VITE_API_URL: "http://localhost:5001"
    ports:
      - "3000:80"
    depends_on:
      - backend
    # You can remove this runtime environment variable since the build arg is what matters:
    # environment:
    #   - VITE_API_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules
